import type { Category, Order, Product } from "@/lib/types"

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Purefoods Tender Juicy Hotdog",
    brand: "Purefoods",
    category: "Hotdogs",
    originalPrice: 285,
    discountedPrice: 185,
    discountPercent: 35,
    image: "/images/hotdogs.jpg",
    quantity: 48,
    unit: "packs",
    expiryDate: "May 12, 2026",
    daysUntilExpiry: 13,
    seller: "Magsaysay Meat Depot",
    sellerRating: 4.8,
    location: "Magsaysay Market, Davao City",
    barangay: "Poblacion District",
    pickupHours: "7:00 AM – 5:00 PM",
    description:
      "Bulk packs of Purefoods Tender Juicy Hotdogs, perfect for resellers and large households. Near-expiry price slash — same great taste, massive savings.",
    weight: "500g",
    packSize: "1 pack = 20 pcs",
    isHot: true,
    isFeatured: true,
  },
  {
    id: "p2",
    name: "CDO Farmhouse Tocino",
    brand: "CDO",
    category: "Tocino",
    originalPrice: 220,
    discountedPrice: 140,
    discountPercent: 36,
    image: "/images/tocino.jpg",
    quantity: 35,
    unit: "packs",
    expiryDate: "May 8, 2026",
    daysUntilExpiry: 9,
    seller: "Gaisano Grand Davao",
    sellerRating: 4.7,
    location: "J.P. Laurel Ave, Bajada, Davao City",
    barangay: "Bajada",
    pickupHours: "8:00 AM – 9:00 PM",
    description:
      "Sweetened pork tocino, a Filipino breakfast staple. CDO Farmhouse quality at clearance pricing. Great for resellers and carinderias.",
    weight: "400g",
    packSize: "1 pack = 10 slices",
    isHot: false,
    isFeatured: true,
  },
  {
    id: "p3",
    name: "Chicken Nuggets Supreme",
    brand: "Quick Chow",
    category: "Frozen Foods",
    originalPrice: 195,
    discountedPrice: 115,
    discountPercent: 41,
    image: "/images/nuggets.jpg",
    quantity: 60,
    unit: "packs",
    expiryDate: "May 20, 2026",
    daysUntilExpiry: 21,
    seller: "Lapanday Cold Storage",
    sellerRating: 4.9,
    location: "McArthur Hwy, Buhangin, Davao City",
    barangay: "Buhangin",
    pickupHours: "6:00 AM – 4:00 PM",
    description:
      "Crispy frozen chicken nuggets in bulk. Perfect for snack shops, school canteens, and home cooking. Cold-storage direct pricing.",
    weight: "1kg",
    packSize: "1 pack = approx. 30 pcs",
    isHot: true,
    isFeatured: false,
  },
  {
    id: "p4",
    name: "Hacienda Bacon Strips",
    brand: "Hacienda",
    category: "Bacon",
    originalPrice: 345,
    discountedPrice: 220,
    discountPercent: 36,
    image: "/images/bacon.jpg",
    quantity: 25,
    unit: "packs",
    expiryDate: "May 6, 2026",
    daysUntilExpiry: 7,
    seller: "SM Supermarket Davao",
    sellerRating: 4.6,
    location: "SM City Davao, Quimpo Blvd",
    barangay: "Matina",
    pickupHours: "10:00 AM – 8:00 PM",
    description:
      "Premium streaky bacon strips, great for breakfast sets, pasta, and catering. Near-expiry bulk clearance from SM Supermarket overstock.",
    weight: "300g",
    packSize: "1 pack = 15 strips",
    isHot: false,
    isFeatured: true,
  },
  {
    id: "p5",
    name: "Magnolia Longaniza",
    brand: "Magnolia",
    category: "Sausages",
    originalPrice: 265,
    discountedPrice: 175,
    discountPercent: 34,
    image: "/images/sausages.jpg",
    quantity: 40,
    unit: "packs",
    expiryDate: "May 15, 2026",
    daysUntilExpiry: 16,
    seller: "Uyanguren Wet Market",
    sellerRating: 4.5,
    location: "Uyanguren St, Toril, Davao City",
    barangay: "Toril",
    pickupHours: "5:00 AM – 3:00 PM",
    description:
      "Authentic sweet Filipino longaniza sausages from Magnolia. Ideal for breakfast, snacks, and resale. Direct from distributor.",
    weight: "250g",
    packSize: "1 pack = 8 links",
    isHot: false,
    isFeatured: false,
  },
  {
    id: "p6",
    name: "Purefoods Honeycured Ham",
    brand: "Purefoods",
    category: "Ham",
    originalPrice: 380,
    discountedPrice: 240,
    discountPercent: 37,
    image: "/images/ham.jpg",
    quantity: 20,
    unit: "packs",
    expiryDate: "May 10, 2026",
    daysUntilExpiry: 11,
    seller: "Lanang Premier",
    sellerRating: 4.8,
    location: "JP Laurel Ave, Lanang, Davao City",
    barangay: "Lanang",
    pickupHours: "9:00 AM – 7:00 PM",
    description:
      "Purefoods honey-cured ham, sliced and vacuum sealed. Perfect for sandwiches, breakfast plates, and catering events. Near-clearance pricing.",
    weight: "500g",
    packSize: "1 pack = 15 slices",
    isHot: false,
    isFeatured: true,
  },
  {
    id: "p7",
    name: "Mega Protein Bundle Deal",
    brand: "Mixed Brands",
    category: "Bundle Deals",
    originalPrice: 1200,
    discountedPrice: 720,
    discountPercent: 40,
    image: "/images/bundle.jpg",
    quantity: 12,
    unit: "bundles",
    expiryDate: "May 12, 2026",
    daysUntilExpiry: 13,
    seller: "Magsaysay Meat Depot",
    sellerRating: 4.8,
    location: "Magsaysay Market, Davao City",
    barangay: "Poblacion District",
    pickupHours: "7:00 AM – 5:00 PM",
    description:
      "Value bundle includes 2x hotdogs, 1x tocino, 1x longaniza, and 1x bacon. Perfect for resellers, eateries, and big families. Best value deal.",
    weight: "~2.5kg total",
    packSize: "5 items per bundle",
    isHot: true,
    isFeatured: true,
  },
]

export const CATEGORIES: Category[] = [
  { id: "hotdogs", label: "Hotdogs", icon: "🌭", color: "#e85d38" },
  { id: "tocino", label: "Tocino", icon: "🥩", color: "#e87038" },
  { id: "frozen-foods", label: "Frozen Foods", icon: "❄️", color: "#38a8e8" },
  { id: "sausages", label: "Sausages", icon: "🫙", color: "#8b5cf6" },
  { id: "bacon", label: "Bacon", icon: "🥓", color: "#f59e0b" },
  { id: "ham", label: "Ham", icon: "🍖", color: "#ec4899" },
  { id: "bundle-deals", label: "Bundle Deals", icon: "📦", color: "#10b981" },
]

export const SELLER_ORDERS: Order[] = [
  {
    id: "ORD-2847",
    buyer: "Maria Santos",
    product: "Purefoods Tender Juicy Hotdog",
    quantity: 3,
    total: 555,
    status: "reserved",
    pickupDate: "May 1, 2026",
    pickupTime: "10:00 AM",
    pickupCode: "F4A-7X29",
  },
  {
    id: "ORD-2848",
    buyer: "Juan dela Cruz",
    product: "CDO Farmhouse Tocino",
    quantity: 5,
    total: 700,
    status: "ready",
    pickupDate: "Apr 30, 2026",
    pickupTime: "2:00 PM",
    pickupCode: "F4A-3K85",
  },
  {
    id: "ORD-2849",
    buyer: "Ana Reyes",
    product: "Magnolia Longaniza",
    quantity: 10,
    total: 1750,
    status: "completed",
    pickupDate: "Apr 28, 2026",
    pickupTime: "9:00 AM",
    pickupCode: "F4A-9M14",
  },
  {
    id: "ORD-2850",
    buyer: "Pedro Lim",
    product: "Mega Protein Bundle Deal",
    quantity: 2,
    total: 1440,
    status: "reserved",
    pickupDate: "May 2, 2026",
    pickupTime: "11:00 AM",
    pickupCode: "F4A-5P66",
  },
]
